#!/Users/siida/anaconda3/bin/python
import sys
import shutil
"""
This program aims to convert a shake file, which is generated by the program SHAKEInp of myPresto tools,
into one which can be inputted to presto_generate_velocities.py in omegagene toolkits 

The problem is as follows:

Look at the following lines of a shake file from SHAKEInp:
--------------------------------------------------------
.
.
.
SHAKE> SHAKE
tip3p_water
      3      1      2      3       -> ;     O  WAT   H1  WAT   H2  WAT
   0.95720  1.51360  0.95720

SHAKE> SHAKE
Cl
    0 -> ;         ###<--- there must be a space between the two arrows.
SHAKE> SHAKE       ###<--- 
Na
    0 -> ;
--------------------------------------------------------
Have a look at the sharp tokens and arrows. The space must be put between the two.
This program does it.
"""

print('Usage:') 
print('    python {0} [shake file] \n'.format(sys.argv[0]))

shk_file = sys.argv[1]

back_name = shk_file + ".bak"
shutil.copy(shk_file, back_name)

with open(shk_file, 'r') as fin:
    contents = fin.readlines()

with open(shk_file, 'w') as fout:
    for i, line in enumerate(contents):
       if line[0:6] == "SHAKE>" and i != 0:
           #print('')
           #print(line.rstrip())
           fout.write('\n')
           fout.write(line.rstrip()+'\n')
       else:
           #print(line.rstrip())
           fout.write(line.rstrip()+'\n')
